### ISSUE TITLE
Setup Kobuki controller

### ISSUE THREAD

**Issue by j3soon** [j3soon/ros2-essentials#14]
Depends on #2 

- Implement a docker-based kobuki controller for ROS2 Humble similar to this ROS1 repo: https://github.com/j3soon/docker-ros-kobuki
- Add a script that can toggle between controlling kobuki in gazebo simulation (#2), and in the realworld (controller implemented in this PR), or both.

Potential ROS2 references:
- https://github.com/kobuki-base/kobuki_core (this should correspond to ros2, as mentioned [here](https://github.com/yujinrobot/kobuki_core))
- https://github.com/kobuki-base/kobuki_ros

**Comment by j3soon** [comment]
Some other references on kobuki docker (ROS 1)
- https://github.com/sarubito/kobuki-docker/tree/master
- https://github.com/sh-hay/kobuki-controller/tree/main

As in our private discussion, please:
- Try out available implementations of kobuki bringup for ROS 2 first. Please discuss with me in advance before deciding to implement from scratch using rosserial, 
- First try out setting up udev rules outside the docker container. Discuss with me before trying to put udev rules inside the docker container.

Thank you.

**Comment by YuZhong-Chen** [comment]
For some reason, I try to put the udev rules inside the Docker container yesterday, and it proved to be successful. 
I'm working with the Arduino Nano device, which is similar to the STM32 on Kobuki.  
However, I'm still in the process of developing the workspace for Kobuki control in ROS2 Humble. 
If I finish it on schedule, we may be able to test it next week ~

**Comment by j3soon** [comment]
Great! Let's schedule a time next week to test it offline.
